image: python:3.10

services:
  - postgres:13

variables:
  POSTGRES_DB: test_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/test_db"

before_script:
  - apt-get update
  - pip install -r requirements.txt
  - pip install pytest

test:
  script:
    - pytest -v